### ISSUE TITLE
/design url paths and file id extraction on them.

### ISSUE THREAD

**Issue by Nhajela** [Axorax/tkforge#2]
Here's my GPT explaining the issue hehe
---

#### Description
The current implementation of the `extract_figma_id` function only accommodates URLs containing `/file/` in the path. However, Figma URLs can also contain different paths such as `/design/`. This limitation results in the function failing to extract the file ID for these alternative URL formats.

#### Current Implementation
The function checks if the URL contains the substring `/file/` in its path. If this condition is not met, the function fails to extract the file ID.

Example:
```python
def extract_figma_id(url):
    if url.startswith('http'):
        url = urlparse(url)
        
        if 'figma.com' in url.netloc and '/file/' in url.path:
            path_parts = url.path.split('/')
            if 'file' in path_parts:
                file_index = path_parts.index('file')
                if file_index + 1 < len(path_parts):
                    return path_parts[file_index + 1]
    return url
```

#### Problematic URL Examples
- `https://www.figma.com/file/abc123/Example-File`
- `https://www.figma.com/design/def456/Example-Design`

The current function only extracts the file ID from URLs similar to the first example, but fails for URLs like the second example.

#### Suggested Fix
The function should be updated to handle multiple valid paths such as `/file/` and `/design/`. This can be achieved by checking for the presence of either path segment in the URL and then extracting the file ID accordingly.

#### Updated Implementation
```python
from urllib.parse import urlparse

def extract_figma_id(url):
    if url.startswith('http'):
        url = urlparse(url)
        
        if 'figma.com' in url.netloc and ('/file/' in url.path or '/design/' in url.path):
            path_parts = url.path.split('/')
            if 'file' in path_parts:
                file_index = path_parts.index('file')
            elif 'design' in path_parts:
                file_index = path_parts.index('design')
            else:
                return None
            
            if file_index + 1 < len(path_parts):
                return path_parts[file_index + 1]
    return None
```

This updated function now checks for both `/file/` and `/design/` in the URL path, ensuring it can extract the file ID from either type of URL.

#### Test Cases
1. `https://www.figma.com/file/abc123/Example-File` should return `abc123`
2. `https://www.figma.com/design/def456/Example-Design` should return `def456`

By incorporating these changes, the function will become more robust and able to handle a wider variety of Figma URL formats.

---

Feel free to adjust the details or examples as needed!

**Comment by Axorax** [comment]
Thanks. I will address the issue as fast as I can. The detailed report really helps me to fix it faster tysm! <3
