### ISSUE TITLE
generation not working properly

### ISSUE THREAD

**Issue by Bulle212** [Axorax/tkforge#5]
This is how it should look like: ![image](https://github.com/user-attachments/assets/d388a416-4804-48c5-8bea-5eaf69bfd865)

But this is how it looks: ![image](https://github.com/user-attachments/assets/d7d01ad7-71dd-4c4e-b4e8-8c59703c8ca3)

**Comment by Axorax** [comment]
hey! can you share your design document or send a screenshot of all the layers? maybe u labelled them incorrectly
