### ISSUE TITLE
Can't make it work.

### ISSUE THREAD

**Issue by julienaub** [Axorax/tkforge#6]
Hi, I tried to use your program, but it doesn't work no matter how I try to use it.

You give 3 exe files in your release. 

When I run the TkForge.exe, I get the window asking for the figma token, file URL, and output path.
Everything is great.

I give the figma token, the file URL and specify the output path... but I always get an error:

"The file ID, token or output path that you provided is invalid!"

Why is that ? How can I fix that?

**Comment by Axorax** [comment]
Hey,

For any help on using the app message me on Discord. You can find my Discord server link here -> https://github.com/axorax/socials

Anyways, I recently helped someone with the same issue. They forgot to add a frame. Maybe your design also has no frame? If that doesn't work, message me on Discord! 😄

**Comment by ChiuHuang** [comment]
Ahh, yes so this is why you got 0 issues

**Comment by Axorax** [comment]
> Ahh, yes so this is why you got 0 issues

yes, because i resolve them
